learning_templates/basicapp/urls.py
from django.urls import path
from basicapp import views


# TEMPLATE TAGGING
app_name =  'basicapp'

# to go to basicapp/relative and basicapp/other
urlpatterns = [
               path('',views.index,name='index'),
               path('relative/', views.relative, name = 'relative'),
               path('other/',views.other,name='other'),
               ]

learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path,include
from basicapp import views
urlpatterns = [
    path('',views.index,name='index'),
    path('admin/', admin.site.urls),
    path('basicapp/',include('basicapp.urls'))
]

learning_templates/basicapp/models.py
from django.db import models

# Create your models here.

learning_templates/basicapp/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    context_dict = {'text':'hello_world', 'number':'27'}
    return render(request,'basicapp/index.html', context_dict)


def other(request):
    return render(request,'basicapp/other.html')

def relative(request):
    return render(request,'basicapp/relative_url_templates.html')

learning_templates/templates/basicapp/base.html
<!DOCTYPE html>
{% load static %}
<!-- {% load my_extras %} -->
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static "css/bootstrap.css "%}"/>
    <title></title>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="{% url 'index' %}">Divya</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-item nav-link" href="{% url 'admin:index' %}">Home</a>
          <a class="nav-item nav-link" href="{% url 'basicapp:friends'%}">Friends</a>
          <a class="nav-item nav-link" href="{% url 'basicapp:hobbies'%}">Hobbies</a>
        </div>
      </div>
    </nav>
    <div class="container">
      {% block body_block %}
      <!-- Anything outside of this will be inherited if you extend -->
      {% endblock %}
    </div>
  </body>
</html>

learning_templates/templates/basicapp/index.html
<!DOCTYPE html>
{% extends "basicapp/base.html" %}
  {% block body_block%}
  <div class="container">
    <div class="jumbotron">
      <h1>Welcome to homepage!</h1>
      <p>Hello I am divya, currently a final year student of IIT Guwahati.
        This website is project undertaken to kill boredom while being quarrantined due to Covid 19 </p>
    </div>
  </div>


  {% endblock %}

learning_templates/templates/basicapp/other.html
<!DOCTYPE html>
{% extends "basicapp/base.html "%}
{% block body_block %}
    <h1>Welcome to other</h1>
    <h2>This is an example of template inheritance! </h2>
{% endblock %}

learning_templates/templates/basicapp/relative_url_templates.html
 <!DOCTYPE html>
 <html lang="en" dir="ltr">
   <head>
     <meta charset="utf-8">
     <title></title>
   </head>
   <body>
     <h1>Welcome to relative_url_templates</h1>
     <!-- basicapp comes from app_name in urls.py -->
     <a href="{% url 'basicapp:other' %}">Link to other</a>

     <!-- instead of <a href="basicapp/other.html"></a> -->

     <a href="{% url 'admin:index' %}">Link to admin</a>

     <a href="{% url 'index' %}">Link to index</a>

   </body>
 </html>